import type { Metadata } from "next";
import Home from "./home";

import "./globals.css";

export const metadata: Metadata = {
  title: "Personal tech Portflio",
  description: "Generated by Vaibhav Sonawane",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html>
        <body>
          <Home/>
        </body>
      </html>
    </>
  );
}
